name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: FTP Deploy
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
      run: |
        lftp -c "
        set ssl:verify-certificate no;
        open -u \"$FTP_USERNAME\",\"$FTP_PASSWORD\" $FTP_HOST;
        mirror -R --verbose \
          --parallel=10 \
          --exclude .git \
          --exclude .vscode \
          ./ $FTP_REMOTE_DIR
        "
